name: Build and Package
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        version: ["8.2", "8.3"]
        arch: [x64]
        ts: [nts, ts]
    runs-on: windows-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup PHP
        id: setup-php
        uses: derickr/setup-php-sdk@b35e22e1afa909692a93556f46ea667037ad593f
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: Build php-ast
        run: |
          cd php-ast
          phpize
          ./configure --enable-ast --with-prefix=${{steps.setup-php.outputs.prefix}}
          nmake
      - name: Package
        run: |
          md binaries
          copy php-ast/LICENSE binaries
          Get-ChildItem -Recurse -Filter "php_ast.dll" | ForEach-Object {Copy-Item -Path $_.FullName -Destination "binaries"}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: php_ast-${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}
          path: binaries